In [1]:
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor(1.00000e-10 *
       [[ 0.0000,  4.6566,  0.0000],
        [ 4.6566,  0.0000,  4.6566],
        [-0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]])


In [3]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


In [4]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[ 1.,  1.],
        [ 1.,  1.]])
